<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYHgH71V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYHgH71V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYHgH71V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYHgH71V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYHgH71V\App_KernelDevDebugContainer([
    'container.build_hash' => 'YHgH71V',
    'container.build_id' => 'b6f5b9b8',
    'container.build_time' => 1748363506,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYHgH71V');
