<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQtelxpe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQtelxpe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQtelxpe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQtelxpe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQtelxpe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qtelxpe',
    'container.build_id' => 'f97f0832',
    'container.build_time' => 1743513681,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQtelxpe');
