<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJCjcg59\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJCjcg59/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJCjcg59.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJCjcg59\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJCjcg59\App_KernelDevDebugContainer([
    'container.build_hash' => 'JCjcg59',
    'container.build_id' => '8c10a67a',
    'container.build_time' => 1748517826,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJCjcg59');
