<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin_menu' => [[], ['_controller' => 'App\\Controller\\AdminController::adminMenu'], [], [['text', '/admin']], [], [], []],
    'admin_add_event' => [[], ['_controller' => 'App\\Controller\\AdminController::addEvent'], [], [['text', '/admin/add-event']], [], [], []],
    'admin_delete_event' => [[], ['_controller' => 'App\\Controller\\AdminController::deleteEvent'], [], [['text', '/admin/delete-event']], [], [], []],
    'admin_finish_event' => [[], ['_controller' => 'App\\Controller\\AdminController::finishEvent'], [], [['text', '/admin/finish-event']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], [], []],
    'place_bet' => [[], ['_controller' => 'App\\Controller\\HomeController::placeBet'], [], [['text', '/place-bet']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\HomeController::logout'], [], [['text', '/logout']], [], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::profile'], [], [['text', '/profile']], [], [], []],
    'change_password' => [[], ['_controller' => 'App\\Controller\\ProfileController::changePassword'], [], [['text', '/profile/change-password']], [], [], []],
    'delete_account' => [[], ['_controller' => 'App\\Controller\\ProfileController::deleteAccount'], [], [['text', '/profile/delete']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\AdminController::adminMenu' => [[], ['_controller' => 'App\\Controller\\AdminController::adminMenu'], [], [['text', '/admin']], [], [], []],
    'App\Controller\AdminController::addEvent' => [[], ['_controller' => 'App\\Controller\\AdminController::addEvent'], [], [['text', '/admin/add-event']], [], [], []],
    'App\Controller\AdminController::deleteEvent' => [[], ['_controller' => 'App\\Controller\\AdminController::deleteEvent'], [], [['text', '/admin/delete-event']], [], [], []],
    'App\Controller\AdminController::finishEvent' => [[], ['_controller' => 'App\\Controller\\AdminController::finishEvent'], [], [['text', '/admin/finish-event']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\HomeController::home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], [], []],
    'App\Controller\HomeController::placeBet' => [[], ['_controller' => 'App\\Controller\\HomeController::placeBet'], [], [['text', '/place-bet']], [], [], []],
    'App\Controller\HomeController::logout' => [[], ['_controller' => 'App\\Controller\\HomeController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\ProfileController::profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::profile'], [], [['text', '/profile']], [], [], []],
    'App\Controller\ProfileController::changePassword' => [[], ['_controller' => 'App\\Controller\\ProfileController::changePassword'], [], [['text', '/profile/change-password']], [], [], []],
    'App\Controller\ProfileController::deleteAccount' => [[], ['_controller' => 'App\\Controller\\ProfileController::deleteAccount'], [], [['text', '/profile/delete']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/register']], [], [], []],
];
