nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']  # Dopuszczone źródło (frontend)
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
    paths:
        '^/api/':  # Dostosuj do ścieżki, której używasz w API
            allow_credentials: true
            allow_origin: ['http://localhost:5173']  # Dopuszczone źródło
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
